// Server-only Firecrawl scrape → exhibit ingestion.
// Called from the server function AND from the agent tool executor.
import type { SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "@/integrations/supabase/types";

type SB = SupabaseClient<Database>;

const FIRECRAWL_ENDPOINT = "https://api.firecrawl.dev/v2/scrape";

type FirecrawlScrapeResponse = {
  success: boolean;
  data?: {
    markdown?: string;
    screenshot?: string; // hosted PNG/JPEG URL
    actions?: {
      screenshots?: string[];
      pdfs?: string[]; // hosted PDF URLs generated by the pdf action
    };
    metadata?: {
      title?: string;
      description?: string;
      sourceURL?: string;
      statusCode?: number;
    };
  };
  error?: string;
};

export type CaptureOptions = {
  /** Route via Firecrawl's enhanced proxy tier for Cloudflare / advanced anti-bot pages. Costs extra credits. */
  stealth?: boolean;
  /** Optional context passed through to the AI reviewer (e.g. why the agent is capturing this URL). */
  agentIntent?: string;
};

async function firecrawlScrape(
  url: string,
  opts: CaptureOptions = {},
): Promise<FirecrawlScrapeResponse["data"]> {
  const apiKey = process.env.FIRECRAWL_API_KEY;
  if (!apiKey) throw new Error("FIRECRAWL_API_KEY is not configured");

  const body: Record<string, unknown> = {
    url,
    // Firecrawl v2 does not accept "pdf" as a format. Generate it as an action instead.
    // Full-page screenshot stays as a fallback. Markdown feeds the agent cache.
    formats: [
      "markdown",
      {
        type: "screenshot",
        fullPage: true,
        quality: 90,
        viewport: { width: 1440, height: 900 },
      },
    ],
    actions: [
      { type: "wait", milliseconds: 4000 },
      { type: "pdf", format: "Letter", landscape: false, scale: 0.9 },
    ],
    onlyMainContent: false,
    blockAds: true,
    mobile: false,
    location: { country: "US", languages: ["en"] },
    maxAge: 3_600_000,
  };
  if (opts.stealth) body.proxy = "enhanced";

  const res = await fetch(FIRECRAWL_ENDPOINT, {
    method: "POST",
    headers: {
      "content-type": "application/json",
      authorization: `Bearer ${apiKey}`,
    },
    body: JSON.stringify(body),
  });

  const text = await res.text();
  let j: FirecrawlScrapeResponse = {} as FirecrawlScrapeResponse;
  try {
    j = JSON.parse(text) as FirecrawlScrapeResponse;
  } catch {
    /* non-JSON body */
  }
  if (!res.ok || !j.success || !j.data) {
    const detail =
      (j.error && j.error !== res.statusText ? j.error : undefined) ||
      text.slice(0, 800) ||
      `HTTP ${res.status}`;
    throw new Error(`Firecrawl: ${detail}`);
  }
  return j.data;
}

function hostFromUrl(u: string): string {
  try {
    return new URL(u).host.replace(/^www\./, "");
  } catch {
    return u.slice(0, 60);
  }
}

export type WebCaptureResult = {
  ok: true;
  exhibit: { id: string; label: string; title: string; mime_type: string };
  source_url: string;
  captured_at: string;
  warnings: string[];
  review?: {
    status: string;
    kept_pages: number[];
    original_page_count: number;
    summary?: string;
    relevance?: string;
    rejected?: boolean;
    note?: string;
  };
};

export async function captureUrlToExhibit(
  supabase: SB,
  projectId: string,
  url: string,
  providedTitle?: string,
  opts: CaptureOptions = {},
): Promise<WebCaptureResult> {
  const warnings: string[] = [];
  const data = await firecrawlScrape(url, opts);

  // Prefer PDF; fall back to screenshot if the PDF format wasn't returned.
  const pdfUrl = data?.actions?.pdfs?.[0];
  const shotUrl = data?.screenshot || data?.actions?.screenshots?.[0];
  const assetUrl = pdfUrl || shotUrl;
  if (!assetUrl || typeof assetUrl !== "string") {
    throw new Error("Firecrawl did not return a PDF or screenshot for this URL");
  }

  const assetRes = await fetch(assetUrl);
  if (!assetRes.ok) throw new Error(`Failed to fetch capture asset: HTTP ${assetRes.status}`);
  const ct = (assetRes.headers.get("content-type") || "").toLowerCase();
  let mime: string;
  let ext: string;
  if (pdfUrl && (ct.includes("pdf") || assetUrl === pdfUrl)) {
    mime = "application/pdf";
    ext = "pdf";
  } else if (ct.includes("jpeg") || ct.includes("jpg")) {
    mime = "image/jpeg";
    ext = "jpg";
  } else {
    mime = "image/png";
    ext = "png";
  }
  const bytes = new Uint8Array(await assetRes.arrayBuffer());

  const capturedAt = new Date().toISOString();
  const title =
    providedTitle?.trim() ||
    data?.metadata?.title?.trim() ||
    `${hostFromUrl(url)} — ${capturedAt.slice(0, 10)}`;

  // Allocate a stable label + append position. Labels are never reused.
  const { allocateNewExhibitSlot } = await import("./exhibit-labels.server");
  const slot = await allocateNewExhibitSlot(supabase, projectId);
  const label = slot.label;
  const nextIdx = slot.order_index;
  const path = `${projectId}/${label}.${ext}`;

  const { error: upErr } = await supabase.storage
    .from("exhibits")
    .upload(path, bytes, { contentType: mime, upsert: true });
  if (upErr) throw upErr;

  const { data: ex, error: eErr } = await supabase
    .from("exhibits")
    .insert({
      project_id: projectId,
      label,
      title,
      order_index: nextIdx,
      storage_path: path,
      original_storage_path: path,
      original_page_count: mime === "application/pdf" ? null : 1,
      size_bytes: bytes.length,
      page_count: 1,
      mime_type: mime,
      original_filename: url.slice(0, 200),
      tags: ["web-capture", ...(opts.stealth ? ["stealth"] : [])],
    })
    .select("id, label, title, mime_type")
    .single();
  if (eErr) throw eErr;

  // Cache header + extracted markdown so the agent can cite the content
  // and the LaTeX render can print a "Source / Retrieved" caption.
  const header = `Source: ${url}  ·  Retrieved: ${capturedAt} UTC`;
  const md = (data?.markdown ?? "").trim();
  const cacheText = md ? `${header}\n\n${md}` : header;
  const { error: cErr } = await supabase
    .from("exhibit_cache")
    .upsert({
      exhibit_id: ex.id,
      extracted_text: cacheText.slice(0, 500_000),
      updated_at: capturedAt,
    });
  if (cErr) warnings.push(`cache: ${cErr.message}`);

  if (!md) warnings.push("No article text extracted; capture saved.");
  if (!pdfUrl) warnings.push("PDF format unavailable — saved screenshot instead.");
  const status = data?.metadata?.statusCode;
  if (status && status >= 400) warnings.push(`Source returned HTTP ${status}`);

  // Autonomously review the capture. For PDFs the AI decides which pages to
  // keep; irrelevant captures (paywalls, cookie walls) come back "rejected".
  let review: WebCaptureResult["review"];
  if (mime === "application/pdf") {
    try {
      const { reviewAndApply } = await import("./exhibit-review.server");
      const outcome = await reviewAndApply({
        supabase,
        projectId,
        exhibitId: ex.id,
        bytes,
        storagePath: path,
        mimeType: mime,
        exhibitTitle: title,
        source: `web:${url}`,
        agentIntent: opts.agentIntent,
      });
      review = {
        status: outcome.status,
        kept_pages: outcome.kept_pages,
        original_page_count: outcome.original_page_count,
        summary: outcome.recommendation?.summary,
        relevance: outcome.recommendation?.relevance,
        rejected: outcome.status === "rejected",
        note: outcome.note,
      };
    } catch (e) {
      warnings.push(`review failed: ${e instanceof Error ? e.message : String(e)}`);
    }
  }

  return {
    ok: true,
    exhibit: ex,
    source_url: url,
    captured_at: capturedAt,
    warnings,
    review,
  };
}

