import { createFileRoute } from "@tanstack/react-router";
import { LegalLayout } from "@/components/LegalLayout";

export const Route = createFileRoute("/terms")({
  head: () => ({
    meta: [
      { title: "Terms of Service — visaworker.ai" },
      {
        name: "description",
        content:
          "The terms that govern your use of visaworker.ai — a drafting tool for O-1A, EB-1A, and NIW petitions. Not a law firm. Not legal advice.",
      },
      { property: "og:title", content: "Terms of Service — visaworker.ai" },
      {
        property: "og:description",
        content:
          "The terms that govern your use of visaworker.ai — a drafting tool for O-1A, EB-1A, and NIW petitions. Not a law firm.",
      },
      { property: "og:type", content: "article" },
      { property: "og:url", content: "https://visaworker.ai/terms" },
      { name: "twitter:card", content: "summary_large_image" },
      { name: "twitter:title", content: "Terms of Service — visaworker.ai" },
      {
        name: "twitter:description",
        content:
          "The terms that govern your use of visaworker.ai — a drafting tool for O-1A, EB-1A, and NIW petitions. Not a law firm.",
      },
      { property: "og:image", content: "https://visaworker.ai/og-image.png" },
      { property: "og:image:width", content: "1200" },
      { property: "og:image:height", content: "630" },
      { property: "og:image:alt", content: "visaworker.ai — the AI drafting agent for your immigration petition." },
      { name: "twitter:image", content: "https://visaworker.ai/og-image.png" },
      { name: "twitter:image:alt", content: "visaworker.ai — the AI drafting agent for your immigration petition." },
    ],
    links: [{ rel: "canonical", href: "https://visaworker.ai/terms" }],
  }),
  component: TermsPage,
});

function TermsPage() {
  return (
    <LegalLayout title="Terms of Service" updated="July 5, 2026">
      <p>
        These Terms of Service (the <strong>"Terms"</strong>) govern your access to
        and use of visaworker.ai (the <strong>"Service"</strong>), operated by
        visaworker.ai (<strong>"we"</strong>, <strong>"us"</strong>, or{" "}
        <strong>"our"</strong>). By creating an account, purchasing a case, or
        otherwise using the Service, you agree to these Terms. If you do not
        agree, do not use the Service.
      </p>

      <h2>1. What the Service is (and is not)</h2>
      <p>
        The Service is a software tool that helps individuals and their
        representatives draft, organize, and compile materials for U.S.
        immigration petitions, including O-1A, EB-1A, and EB-2 NIW filings.
      </p>
      <p>
        <strong>
          We are not a law firm. We do not provide legal advice, legal opinions,
          or legal representation, and no attorney-client relationship is
          created by your use of the Service.
        </strong>{" "}
        Output produced by the Service — including drafts, letters, exhibit
        lists, and citations — is generated by software and artificial
        intelligence models and is provided for your review, editing, and
        independent verification.
      </p>
      <p>
        For legal advice about your specific situation, please consult a
        licensed immigration attorney in your jurisdiction.
      </p>

      <h2>2. No guaranteed outcome and no case-suitability review</h2>
      <p>
        USCIS adjudications depend on many factors outside our control,
        including officer discretion, current policy, evidentiary sufficiency,
        and the individual merits of your case. <strong>We do not guarantee</strong>{" "}
        approval, avoidance of a Request for Evidence, any particular processing
        time, or any other outcome. Prior results do not predict future
        outcomes.
      </p>
      <p>
        We also do not review or evaluate whether your background, evidence, or
        credentials are sufficient to meet the legal standards for O-1A, EB-1A, or
        EB-2 NIW classification. You are solely responsible for deciding whether
        your case is ready to file with USCIS and for consulting any attorney or
        representative you choose.
      </p>

      <h2>3. Eligibility and accounts</h2>
      <p>
        You must be at least 18 years old and able to form a binding contract
        to use the Service. You are responsible for maintaining the
        confidentiality of your account credentials and for all activity that
        occurs under your account.
      </p>

      <h2>4. Your responsibilities</h2>
      <ul>
        <li>
          You are solely responsible for reviewing every draft, citation, and
          exhibit produced by the Service before using, sharing, or submitting
          it anywhere — including to USCIS.
        </li>
        <li>
          You are responsible for the accuracy and lawfulness of the content
          you upload, including that you have the right to upload it and that
          it does not contain material you are not authorized to share.
        </li>
        <li>
          You will not use the Service to generate content that is fraudulent,
          defamatory, unlawful, or intended to deceive an adjudicator or third
          party.
        </li>
        <li>
          You will not attempt to reverse engineer the Service, resell it,
          probe it for vulnerabilities without written permission, or use it
          to build a competing product.
        </li>
      </ul>

      <h2>5. Payments, token budgets, and refunds</h2>
      <p>
        Cases are sold on a one-time basis for a fixed price per petition,
        which includes an initial token budget for AI-generated drafting.
        Additional tokens may be purchased as top-ups. Prices are shown at
        checkout and are charged in U.S. dollars via our payment processor,
        Stripe.
      </p>
      <p>
        <strong>All purchases are non-refundable.</strong> Once you open a case,
        the workspace is live and drafting resources are allocated. We do not
        issue refunds for change of mind, unused tokens, or case outcomes.
      </p>
      <p>
        A "token" corresponds to raw input and output tokens consumed by the
        underlying AI models on your behalf. When your case's token budget is
        exhausted, new AI turns are blocked until you top up, but you retain
        the ability to view, export, and download your case.
      </p>

      <h2>6. Intellectual property</h2>
      <p>
        You retain ownership of the content you upload and the materials the
        Service drafts for you based on your inputs (your{" "}
        <strong>"Case Content"</strong>). You grant us a limited, non-exclusive
        license to host, process, and display your Case Content solely for the
        purpose of operating the Service for you.
      </p>
      <p>
        We retain all rights in the Service itself, including software,
        templates, prompts, model orchestration, and the user interface. We do
        not use your Case Content to train third-party models.
      </p>

      <h2>7. Third-party services</h2>
      <p>
        The Service relies on the third-party subprocessors listed below to
        operate. Your use of the Service is also subject to those providers'
        terms and privacy practices to the extent your data is processed by
        them. This list may change as we improve the Service; material changes
        will be reflected here.
      </p>
      <ul>
        <li>
          <strong>Lovable</strong> (Lovable Labs, Inc.) — application hosting,
          edge runtime, and static asset delivery.
        </li>
        <li>
          <strong>Supabase</strong> (Supabase, Inc.) — authentication, primary
          database, and file storage for your Case Content.
        </li>
        <li>
          <strong>Stripe</strong> (Stripe, Inc.) — payment processing for case
          purchases and token top-ups. Card details are handled by Stripe and
          are never sent to or stored by us.
        </li>
        <li>
          <strong>Anthropic</strong> (Anthropic, PBC) — Claude large-language
          models used to draft, summarize, and organize petition content.
          Anthropic does not train its models on data submitted through the
          API.
        </li>
        <li>
          <strong>Firecrawl</strong> (Sideguide Technologies, Inc.) — server-side
          web scraping used to capture the public URLs you provide as
          exhibits (e.g., news articles, faculty pages, publication listings).
        </li>
        <li>
          <strong>LaTeX compilation services</strong> — the final petition PDF
          is produced by a LaTeX build service. By default we call the
          open-source project <em>latex-on-http</em> hosted at{" "}
          <code>latex.ytotech.com</code>, and may fall back to{" "}
          <code>latexonline.cc</code>. The LaTeX source we send to these
          services contains the drafted petition content (which can include
          your name, employer, and other personal information you provided).
          If this is not acceptable for your case, do not compile the PDF
          through the Service and instead export the source for local
          compilation.
        </li>
        <li>
          <strong>Resend</strong> (Resend, Inc.) — transactional email delivery,
          including sign-in links, password resets, receipts, referral notices,
          and other account-related messages. Resend receives your email
          address and the contents of the messages we send you.
        </li>
        <li>
          <strong>PostHog</strong> (PostHog, Inc.) — product analytics and
          session-level usage metrics used to understand how the Service is
          used and to diagnose issues. PostHog receives pseudonymous usage
          events, page views, and device/log metadata; we do not send your
          Case Content to PostHog.
        </li>
        <li>
          <strong>SwiftLaTeX</strong> (open-source, MIT) — an in-browser WASM
          LaTeX engine used to preview your petition locally in your browser.
          It runs entirely on your device and does not transmit your content
          to a third-party server.
        </li>
        <li>
          <strong>Google Fonts</strong> (Google LLC) — web fonts served to
          your browser when you load the site.
        </li>
        <li>
          <strong>YouTube</strong> (Google LLC) — used to embed product demo
          videos on our marketing pages. YouTube may set cookies and collect
          usage data when a video player is loaded, subject to Google's
          privacy policy.
        </li>
      </ul>


      <h2>8. Disclaimers</h2>
      <p>
        THE SERVICE IS PROVIDED <strong>"AS IS"</strong> AND{" "}
        <strong>"AS AVAILABLE"</strong>, WITHOUT WARRANTIES OF ANY KIND, WHETHER
        EXPRESS, IMPLIED, OR STATUTORY, INCLUDING WARRANTIES OF MERCHANTABILITY,
        FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, AND ANY WARRANTY
        THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR SECURE. AI
        OUTPUT MAY BE INACCURATE, INCOMPLETE, OR MISLEADING AND MUST BE
        INDEPENDENTLY VERIFIED BEFORE USE.
      </p>

      <h2>9. Limitation of liability</h2>
      <p>
        TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT WILL WE BE LIABLE
        FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE
        DAMAGES, OR ANY LOSS OF PROFITS, REVENUE, DATA, OR GOODWILL, ARISING
        OUT OF OR RELATED TO YOUR USE OF THE SERVICE. OUR TOTAL LIABILITY FOR
        ANY CLAIM ARISING OUT OF OR RELATED TO THE SERVICE WILL NOT EXCEED THE
        AMOUNTS YOU PAID US FOR THE SERVICE IN THE TWELVE (12) MONTHS
        PRECEDING THE EVENT GIVING RISE TO THE CLAIM.
      </p>

      <h2>10. Indemnification</h2>
      <p>
        You will indemnify and hold us harmless from any claims, damages, or
        expenses (including reasonable attorneys' fees) arising from (a) your
        Case Content, (b) your use of the Service in violation of these Terms
        or applicable law, or (c) any submission you make to USCIS or another
        third party based on Service output.
      </p>

      <h2>11. Termination</h2>
      <p>
        You may stop using the Service at any time and request deletion of your
        account by writing to{" "}
        <a href="mailto:support@visaworker.ai">support@visaworker.ai</a>. We may
        suspend or terminate your access if we reasonably believe you have
        violated these Terms or are using the Service unlawfully. Sections that
        by their nature should survive termination will survive.
      </p>

      <h2>12. Changes to the Service or these Terms</h2>
      <p>
        We may update the Service and these Terms from time to time. Material
        changes will be communicated by updating the "Last updated" date above
        and, when appropriate, by in-app notice. Your continued use of the
        Service after changes take effect constitutes acceptance of the updated
        Terms.
      </p>

      <h2>13. Governing law</h2>
      <p>
        These Terms are governed by the laws of the State of Delaware, without
        regard to conflict-of-laws principles. Any dispute will be resolved in
        the state or federal courts located in Delaware, and you consent to
        personal jurisdiction there.
      </p>

      <h2>14. Contact</h2>
      <p>
        Questions about these Terms? Reach us at{" "}
        <a href="mailto:legal@visaworker.ai">legal@visaworker.ai</a>.
      </p>

      <h2>15. Referral Program</h2>
      <p>
        The referral program lets you share a personal link with others.
        Referral credit is earned only when the referred user pays for a case
        (a paid unlock). When someone pays for their first case through your
        link, they receive a $50 discount on that case and you earn $50 in
        referral credit in your account. Free preview usage and
        bring-your-own-key usage do not qualify for referral credit because
        we are not paid for those cases. If a referred user starts on free
        preview or bring-your-own-key and later upgrades to a paid unlock,
        the referral credit is awarded at the time of that paid unlock.
      </p>
      <p>
        You may earn referral credit on up to five paid referrals per account,
        for a maximum of $250 in credit. Credits have no cash value until they
        are cashed out, and they can be used to pay for your own cases or token
        top-ups on the Service. You may request a cash-out only after you have
        earned credit from at least two paid referrals and have at least $50.00
        in available credit. Cash-out requests are subject to verification, may
        require you to provide payout information through a third-party payout
        provider, and may take time to process.
      </p>
      <p>
        Credits are not transferable, may not be sold or exchanged, and may be
        withheld or reversed if we detect fraud, abuse, self-referral, a refund
        or chargeback on the referred case, or any other conduct that violates
        these Terms or the spirit of the program. We may change, pause, or end
        the referral program at any time.
      </p>

      <h2>16. Partner law firm directory</h2>
      <p>
        The Service may include a directory of immigration law firms that may
        offer a discounted rate to VisaWorker users for review and filing of
        petitions drafted on the Service (each a <strong>"Partner Firm"</strong>).
        Partner Firms are independent third parties. We do not employ them,
        supervise their work, or control the advice or services they provide.
      </p>
      <p>
        <strong>
          We make no guarantees, representations, or warranties about any
          Partner Firm or the outcome of any matter they handle.
        </strong>{" "}
        Listing a firm, marking it as a partner, or displaying its fees does not
        mean we endorse its services, guarantee its availability, or vouch for
        the quality of its work. Any engagement you enter into with a Partner
        Firm is strictly between you and that firm.
      </p>
      <p>
        <strong>
          We are not responsible for any act, omission, error, delay, or
          negligence of a Partner Firm, including any legal advice, filing,
          communication, or representation they provide.
        </strong>{" "}
        If you have a dispute with a Partner Firm, you must resolve it directly
        with that firm. We do not receive referral fees, kickbacks, or any other
        compensation from Partner Firms for listings, leads, or engagements.
      </p>
      <p>
        You remain solely responsible for choosing any attorney or
        representative, reviewing any work product, and deciding whether and
        when to file with USCIS. Nothing on the Service creates an
        attorney-client relationship between you and us, or between you and any
        Partner Firm, until you separately engage that firm.
      </p>
    </LegalLayout>
  );
}
