#!/usr/bin/env bash
# build-public-repo.sh
#
# Produces a clean tree suitable for pushing to the public OSS mirror.
# The private working tree is never modified.
#
# Usage:
#   bash scripts/build-public-repo.sh                # writes to ../visaworker-oss
#   bash scripts/build-public-repo.sh /path/to/out   # writes to /path/to/out
#
# What it does:
#   1. copy working tree → target (excluding EE + private paths), via rsync or,
#      when rsync is absent, `git archive` of committed HEAD. This also drops
#      EE-only routes that live outside src/ee/: the hosted Stripe webhook,
#      transactional/lifecycle email hooks, Meta CAPI test, the demo reset cron,
#      the public letter-sharing routes, and the hosted-only admin dashboard +
#      referrals-dashboard pages. Their typed <Link>s are carried by the EE
#      HeaderNavExtras component (stubbed to null in the open build), so no
#      surviving open code references these routes. The generated
#      src/routeTree.gen.ts is excluded too (see note below).
#   2. drop docs/oss/gitignore.public into target as .gitignore
#   3. swap src/ee/index.ts for src/ee/index.stub.ts, then delete src/ee (only
#      the barrel stays as a re-export shell that returns "ee_required")
#   4. sanitize supabase/config.toml (strip project_id and any *_id refs)
#   5. copy docs/oss/README.public.md → README.md
#   6. regenerate bun.lock against public npm (the working tree's lock pins an
#      internal registry mirror that public users cannot reach)
#
# Route tree: src/routeTree.gen.ts is generated by the TanStack Start plugin and
# imports every route module, so it can't be copied verbatim once EE routes are
# excluded (it would import files that no longer exist). It is left out of the
# mirror and gitignored there; the plugin regenerates it from the surviving
# routes on the first `vite build`. The public CI (.github/workflows/ci.yml)
# runs the build before the typecheck for this reason.
#
# What it does NOT do (manual follow-ups called out in .lovable/oss-audit.md):
#   - Split supabase/migrations into open-only + EE (schema baseline
#     consolidation happens by hand; the current script omits migrations
#     entirely and prints a reminder).
#   - Regenerate src/integrations/supabase/types.ts against the open-only
#     schema.
#   - Run gitleaks/trufflehog over the resulting tree.
#   - Rotate BYOK_ENCRYPTION_KEY and re-encrypt rows in the live DB.

set -euo pipefail

SRC="$(cd "$(dirname "$0")/.." && pwd)"
DEST="${1:-$(dirname "$SRC")/visaworker-oss}"

echo "→ source: $SRC"
echo "→ target: $DEST"

if [ -e "$DEST" ]; then
  echo "target exists; refusing to overwrite. remove it first." >&2
  exit 1
fi

mkdir -p "$DEST"

# Paths never copied into the public mirror. Two groups:
#   - build/vcs/env noise that is untracked anyway (so `git archive` drops it
#     for free), and
#   - tracked private/EE paths that MUST be removed explicitly.
EXCLUDES=(
  # untracked noise (only matters for the rsync path)
  '.git' 'node_modules' 'dist' '.output' '.tanstack' '.wrangler' '.vinxi'
  '.turbo' '.cache' '.env' '.env.local' '.env.development' '.env.production'
  # tracked private / EE paths
  '.lovable' 'AGENTS.md' 'public/brand' 'public/product-hunt'
  'src/ee' 'ee' 'supabase/migrations' 'src/routeTree.gen.ts'
  'src/routes/api/public/hooks/reset-demo.ts'
  'src/routes/api/public/hooks/lifecycle-emails.ts'
  'src/routes/api/public/webhooks.stripe.ts'
  'src/routes/api/public/meta-capi-test.ts'
  'src/routes/api/public/unsubscribe.ts'
  'src/routes/api/public/auth/send-email.ts'
  'src/routes/api/public/letter.$token.pdf.ts'
  'src/routes/letter.$token.tsx'
  'src/routes/_authenticated/admin.tsx'
  'src/routes/_authenticated/account.referrals.tsx'
)

if command -v rsync >/dev/null 2>&1; then
  echo "→ copying working tree with rsync"
  rsync_args=()
  for e in "${EXCLUDES[@]}"; do rsync_args+=("--exclude=$e"); done
  rsync -a "${rsync_args[@]}" "$SRC/" "$DEST/"
elif git -C "$SRC" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  # No rsync: ship the committed tree via `git archive` (tracked files only, so
  # node_modules / build dirs / .env* are excluded for free), then delete the
  # tracked private/EE paths. NOTE: this ships committed HEAD, not uncommitted
  # working-tree changes — commit before publishing.
  echo "→ rsync not found; copying committed HEAD with git archive"
  git -C "$SRC" archive --format=tar HEAD | tar -x -C "$DEST"
  for e in "${EXCLUDES[@]}"; do rm -rf "${DEST:?}/$e"; done
else
  echo "need either rsync or a git checkout to build the mirror" >&2
  exit 1
fi

# .gitignore for the public repo
cp "$SRC/docs/oss/gitignore.public" "$DEST/.gitignore"

# Swap in the EE stub barrels (open build gets `ee_required` on any EE call)
mkdir -p "$DEST/src/ee"
cp "$SRC/src/ee/index.stub.ts" "$DEST/src/ee/index.ts"
cp "$SRC/src/ee/server.stub.ts" "$DEST/src/ee/server.ts"
cp "$SRC/src/ee/README.md" "$DEST/src/ee/README.md"

# Sanitize supabase/config.toml — strip project_id
if [ -f "$SRC/supabase/config.toml" ]; then
  mkdir -p "$DEST/supabase"
  sed -E '/^project_id\s*=/d' "$SRC/supabase/config.toml" > "$DEST/supabase/config.toml"
fi

# Derive OSS-safe supabase types by stripping EE tables/functions/columns
# per docs/oss/ee-db-manifest.json. Runs in-place on the target tree.
if [ -f "$SRC/scripts/generate-open-types.mjs" ]; then
  node "$SRC/scripts/generate-open-types.mjs" \
    --in "$DEST/src/integrations/supabase/types.ts" \
    --out "$DEST/src/integrations/supabase/types.ts" \
    --manifest "$SRC/docs/oss/ee-db-manifest.json"
fi

# Ship the schema dumper + manifest so downstream forks can regenerate the
# baseline against their own DB.
mkdir -p "$DEST/docs/oss"
cp "$SRC/docs/oss/ee-db-manifest.json" "$DEST/docs/oss/ee-db-manifest.json"
if [ -f "$SRC/scripts/dump-open-schema.sh" ]; then
  cp "$SRC/scripts/dump-open-schema.sh" "$DEST/scripts/dump-open-schema.sh"
  chmod +x "$DEST/scripts/dump-open-schema.sh"
fi

# Install the consolidated open-schema baseline as the mirror's single migration.
# It is committed at docs/oss/schema-baseline.sql (EE tables/functions already
# stripped per the manifest, validated to apply against a fresh Postgres), so
# publishing needs no live-DB access. Regenerate it with dump-open-schema.sh
# whenever the production schema changes.
if [ -f "$SRC/docs/oss/schema-baseline.sql" ]; then
  mkdir -p "$DEST/supabase/migrations"
  cp "$SRC/docs/oss/schema-baseline.sql" \
     "$DEST/supabase/migrations/00000000000000_open_baseline.sql"
  echo "→ installed open-schema baseline as supabase/migrations/00000000000000_open_baseline.sql"
else
  echo "  ⚠ docs/oss/schema-baseline.sql missing — mirror will ship with NO DB schema" >&2
fi

# README swap
if [ -f "$SRC/docs/oss/README.public.md" ]; then
  cp "$SRC/docs/oss/README.public.md" "$DEST/README.md"
fi

# Rewrite the lockfile's registry host to public npm. The working tree's
# bun.lock pins an internal Google Artifact Registry mirror
# (europe-west4-npm.pkg.dev/<proj>/<repo>/...) that public users and public CI
# cannot reach, so a verbatim copy would 403 on the first install. Those tarball
# paths map 1:1 to registry.npmjs.org, so a host swap keeps EXACT versions while
# making every URL public. (A fresh `bun install` would instead drift to newer
# patch versions and can break the typecheck — do not do that here.)
if [ -f "$DEST/bun.lock" ]; then
  sed -E -i.bak 's#https://[a-z0-9-]+\.pkg\.dev/[^/]+/[^/]+/#https://registry.npmjs.org/#g' "$DEST/bun.lock"
  rm -f "$DEST/bun.lock.bak"
  if grep -q "pkg.dev" "$DEST/bun.lock"; then
    echo "  ⚠ some private registry URLs remain in bun.lock — review before publishing" >&2
  else
    echo "→ rewrote bun.lock registry host → registry.npmjs.org (versions preserved)"
  fi
fi

cat <<EOF

✓ public tree written to: $DEST

MANUAL FOLLOW-UPS before first push:
  1. Verify the mirror builds:
       cd $DEST && bun install --frozen-lockfile && bun run build && bunx tsc --noEmit
  2. Run gitleaks over $DEST (full history scan)
  3. Rotate BYOK_ENCRYPTION_KEY in the live DB (see .lovable/oss-audit.md)
  4. cd $DEST && git init && git add -A && git commit -m "Initial commit"

  (The open-schema baseline is installed automatically from
   docs/oss/schema-baseline.sql — regenerate it with dump-open-schema.sh only
   when the production schema changes.)
EOF

